version: "3.8"
services:
  server:
    image: "infracloudio/csvserver:latest"
    ports:
      - "9393:9300"
    environment:
      CSVSERVER_BORDER: Orange
    volumes:
      - ./inputFile:/csverver/inputdata

