version: "3.8"
services:
  server:
    image: "infracloudio/csvserver:latest"
    ports:
      - "9393:9300"
    environment:
      CSVSERVER_BORDER: Orange
    volumes:
      - ./inputFile:/csverver/inputdata
  prometheus:
    image: "prom/prometheus:v2.22.0"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml

